#Global
ButtonClose = ""
#First page
MainLabel = ""
TeamLabel = "" # Don't forget 2 spaces at start
ButtonContinue = ""
# Second page
ChoosePathLabel = ""
ButtonInstall = ""
LabelPath = ""
ButtonBrowse = ""
#Integrity error
IntegrityError = ""
#Injection error
InjectionError = ""
#Third page
ThanksLabel = ""
